### ISSUE TITLE
Creazione cartelle

### ISSUE THREAD

**Issue by thegithubr** [francinicla/Tombola-Bingo#3]
Ti segnalo che nelle cartelle della tombola, nella prima colonna sono inseriti i numeri da 1 a 9, nella seconda colonna da 10 a 19 e così via. Nell'ultima colonna i numeri da 80 a 90.
Il tuo programma, invece, mostra nella prima colonna i numeri da 1 a 10, nella seconda da 11 a 20 e così via.

Sarebbe anche simpatico se implementassi un metodo manuale per la creazione delle cartelle magari permettendone il salvataggio su file.

Complimenti per il tuo lavoro.
Saluti

**Comment by francinicla** [comment]
TI ringrazio per la segnalazione :)
Faccio una verifica e poi ti faccio sapere!

Grazie anche per il suggerimento, lo terrò a mente per la versione 2.0!  :)

**Comment by francinicla** [comment]
Problema risolto con la versione GuiTombola0.9.2.py
